language: python
python:
        - 3.5
install:
        - pip install unittest2
        - pip install coveralls
script:
        - make test
        - coverage run test_rpn.py
after_success:
        coveralls
